### ISSUE TITLE
Please add support for APCu

### ISSUE THREAD

**Issue by innobrig** [apix/cache#29]
Since APC as a caching engine is no longer supported, please add support for APCu. This could be as simple as cloning your APC class and renaming the methods to apcu_*

**Comment by frqnck** [comment]
Hi @innobrig 

`APCu` is backwards compatibile with `APC` so you can should be able to use `Apix\Cache\Apc` out of the box. e.g. `$cache = Cache\Factory::getPool('apc');` 

Is this not working any longer?

**Comment by frqnck** [comment]
The test suite should testify of this actually.

Seems Travis has a few builds failing -- will check this out for you.

I vaguely remember testing `Apix\Cache\Apc` with `APCu` on PHP7 and HHVM and it was working.

**Comment by innobrig** [comment]
If you look at http://php.net/manual/en/book.apcu.php you'll see that the API calls are now called (ie: prefixed by) "apcu_" ... I'm not 100% sure, but I seem to recall that the original apc calls were prefixed by "apc_"

**Comment by frqnck** [comment]
It seems that `APCu` no longer ship with the backward compatibility module (apcu-bc) so as requested I have added the `Apix\Cache\Apcu` backend which uses the `apcu-*` functions specifically. Thank you for pointing this out in the first place.

You can use the factory class follow: `$cache = Cache\Factory::getPool('apcu');`
