### ISSUE TITLE
AbstractPdo::flush() drops the cache table on flush(true)

### ISSUE THREAD

**Issue by BlairCooper** [apix/cache#40]
## Bug Report

The implementation of the AbstractPdo classes drops the cache table on flush(true). This results on a exception being thrown if the cache is subsequently accessed as the cache table no longer exists.

### Description

Additionally the implementation does not match the documentation for the method provided by Adapter::flush().

### More details

  - Apix-cache version: 1.3.4
  - Operating System: RHEL 7.5, Windows 10
  - PHP Version: 7.2.14, 7.3.14
  - etc..

**Comment by frqnck** [comment]
Hi @BlairCooper, thanks for pointing this out and providing the fix which has been rolled out as a part of version 1.3.5 -- many thanks.
